JustSpare/Web/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Dal;
using Service;
using Web.Models;

namespace Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly AccountService _accountService;
        private readonly DonateService _donateService;
        private readonly ItemsService _itemsService;

        private int _userId;

        public ItemsController(DonateService donateService, AccountService accountService, ItemsService itemsService)
        {
            _donateService = donateService;
            _accountService = accountService;
            _itemsService = itemsService;
        }

        public ActionResult DonateItems()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DonateItems(DonateViewModel donateViewModel)
        {
            if (!ModelState.IsValid)
                return View("DonateItems", donateViewModel);

            var username = User.Identity.Name;

            _donateService.DonateItem(donateViewModel.Description, donateViewModel.ItemType, donateViewModel.Name,
                donateViewModel.NumberOf, donateViewModel.QualityType, username);

            return RedirectToAction("UserListOfItems");
        }

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult ItemsClaimed()
        {
            _userId = _accountService.GetUserByName(User.Identity.Name).Id;
            var itemsClaimed = _itemsService.GetClaimedItems(_userId);

            var donateViewModels = GenerateDonateViewModels(itemsClaimed);

            return View(donateViewModels);
        }

        [HttpPost]
        public ActionResult ListOfItems(List<DonateViewModel> claimedItems)
        {
            _userId = _accountService.GetUserByName(User.Identity.Name).Id;
            var claimedIds = new List<int>();
            foreach (var item in claimedItems)
                if (item.ItemSelected)
                    claimedIds.Add(item.Id);

            _itemsService.CreateClaim(_userId, claimedIds);

            return RedirectToAction("ItemsClaimed");
        }

        public ActionResult ListOfItems()
        {
            var allItems = _itemsService.GetAllUnclaimedItems();

            var donateViewModels = GenerateDonateViewModels(allItems);

            return View(donateViewModels);
        }

        public ActionResult UserListOfItems()
        {
            var allItems = _itemsService.GetUserItems(User.Identity.Name);

            var donateViewModels = GenerateDonateViewModels(allItems);

            return View(donateViewModels);
        }

        private List<DonateViewModel> GenerateDonateViewModels(List<Item> itemsClaimed)
        {
            var donateViewModels = new List<DonateViewModel>();
            foreach (var item in itemsClaimed)
                donateViewModels.Add(new DonateViewModel
                {
                    Description = item.Description,
                    DonatedBy = _accountService.GetUserById(item.DonatedByUserId).ContactName,
                    ItemType = (Enums.ItemType) Enum.Parse(typeof(Enums.ItemType), item.ItemType.ToString()),
                    Name = item.Name,
                    NumberOf = item.NumberOf,
                    QualityType =
                        (Enums.QualityType) Enum.Parse(typeof(Enums.QualityType), item.QualityType.ToString()),
                    Id = item.Id
                });
            return donateViewModels;
        }
    }
}

JustSpare/Web/Views/Items/DonateItems.cshtml
@model Web.Models.DonateViewModel
@{
    ViewBag.Title = "DonateItems";
    Layout = "../Shared/_Secure.cshtml";
}

<h2>Donate Items</h2>


<div class="row">
    <div class="col-lg-12">

        @using (Html.BeginForm("DonateItems", "Items", FormMethod.Post, new { id = "Form Name", @class = "form-horizontal" }))
        {
            <div class="form-group">
                @Html.LabelFor(c => c.Name, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-4 col-lg-4 col-md-4">
                    @Html.TextBoxFor(c => c.Name, new { @class = "form-control", style = "width:100%", placeholder = "Item name" })
                    @Html.ValidationMessageFor(c => c.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(c => c.Description, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-4 col-lg-4 col-md-4">
                    @Html.TextAreaFor(c => c.Description, new { @class = "form-control", style = "width:100%", placeholder = "Description" })
                    @Html.ValidationMessageFor(c => c.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(c => c.NumberOf, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-4 col-lg-4 col-md-4">
                    @Html.TextBoxFor(c => c.NumberOf, new { @class = "form-control", style = "width:100%", placeholder = "Number of item" })
                    @Html.ValidationMessageFor(c => c.NumberOf, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(c => c.ItemType, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-4 col-lg-4 col-md-4">
                    @Html.EnumDropDownListFor(c=>c.ItemType, new { @class = "form-control", style = "width:100%"})
                    @Html.ValidationMessageFor(c => c.ItemType, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(c => c.QualityType, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-4 col-lg-4 col-md-4">
                    @Html.EnumDropDownListFor(c => c.QualityType, new { @class = "form-control", style = "width:100%" })
                    @Html.ValidationMessageFor(c => c.QualityType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Donate!!</button>
                </div>
            </div>
        }
    </div>
</div>


@*public string Name { get; set; }
public int NumberOf { get; set; }

public string Description { get; set; }

public Enums.QualityType QualityType { get; set; }
public Enums.ItemType ItemType { get; set; }*@

JustSpare/Web/Views/Items/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Donate Items</h2>

JustSpare/Web/Views/Items/ItemsClaimed.cshtml
@model List<Web.Models.DonateViewModel>
@{
    ViewBag.Title = "ItemsClaimed";
    Layout = "~/Views/Shared/_Secure.cshtml";
}

@{
    if (Model.Count > 0)
    {
        <h2>Items Claimed</h2>

        Html.RenderPartial("ListOfItemsPartial", Model);
    }
    else
    {
        <h3>You haven't claimed any items!</h3>
    }
}

<br/>
<br/>
<br/>
<br/>

JustSpare/Web/Views/Items/ListOfItems.cshtml
@model List<Web.Models.DonateViewModel>
@{
    ViewBag.Title = "ListOfItems";
    Layout = "../Shared/_Secure.cshtml";
}

<h2>Donations</h2>

<div class="row">
    <div class="col-lg-3">
    </div>


    @using (Html.BeginForm("ListOfItems", "Items", FormMethod.Post, new {id = "loginform", onsubmit = "return confirm('Are you sure you wish to claim these items?');"}))
    {
        <div class="col-lg-6">
            <div class="list-group">

                @for (var i = 0; i < Model.Count; i++)
                {
                    @Html.HiddenFor(c => c[i].Id)
                    <a class="list-group-item">
                        <div class="pull-right btn-group" data-toggle="buttons">
                            <label class="btn btn-primary">
                                @Html.CheckBoxFor(c => c[i].ItemSelected) Claim
                            </label>
                        </div>
                        <h4 class="list-group-item-heading">@Model[i].Name</h4>
                        <p class="list-group-item-text">@Model[i].Description</p>
                        <p class="list-group-item-text text-success">@Model[i].ItemType</p>
                        <p class="list-group-item-text text-primary">Amount Available: @Model[i].NumberOf</p>
                        <p class="list-group-item-text text-primary">@Model[i].QualityType</p>

                    </a>
                }

            </div>
            
            @{
                if (Model.Count != 0)
                {
                    <button type="submit" class="btn btn-danger">Make Claim</button>
                }
                else
                {
                    <h4>Unfortunately there is nothing available at the moment :-(</h4>
                    <h4>Please look back later!</h4>
                }
            }
            

        </div>
    }
</div>

JustSpare/Web/Views/Items/UserListOfItems.cshtml
@using Web.Models
@model List<DonateViewModel>
@{
    ViewBag.Title = "UserListOfItems";
    Layout = "../Shared/_Secure.cshtml";
}



@{
    if (Model.Count > 0)
    {
        <h2>Your Donations</h2>

        Html.RenderPartial("ListOfItemsPartial", Model);
    }
    else
    {
        <h3>You haven't donated anything just yet!</h3>
    }
}

<br/>
<br />
<br />
<br />